name: citra-build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-2022
    strategy:
      matrix:
        target: ["msvc"]
    defaults:
      run:
        shell: ${{ (matrix.target == 'msys2' && 'msys2') || 'bash' }} {0}
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
      OS: windows
      TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v7
        with:
          ref: master-win7
          submodules: recursive

      - name: List files
        run: ls "${{ github.workspace }}/externals/glslang"
        
      - name: Update SPIR-V tools
        run: python3 "${{ github.workspace }}\externals\glslang\update_glslang_sources.py"
        
      - name: Set up cache
        uses: actions/cache@v6
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-

      - name: Download Qt
        run: git clone https://github.com/${{ github.repository_owner }}/Qt-Win-Shared C:/Qt
        
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        if: ${{ matrix.target == 'msvc' }}
        
      - name: Install extra tools (MSVC)
        run: choco install ccache wget
        if: ${{ matrix.target == 'msvc' }}
            
      - name: Disable line ending translation
        run: git config --global core.autocrlf input
        
      - name: Build
        run: ./.ci/windows.sh
        
      - name: Pack
        run: ./.ci/pack.sh
        
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.OS }}-${{ env.TARGET }}
          path: artifacts/
